<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="EPKZKARW0363" ignored="0" name="testSum" tests="22" failures="5" timestamp="30 Oct 2017 08:02:44 GMT" time="0.05" errors="0">
  <testcase name="testSum" time="0.001" classname="com.epam.unittesting.tests.SumCalculatorTest"/>
  <testcase name="testSum" time="0.0" classname="com.epam.unittesting.tests.SumCalculatorTest"/>
  <testcase name="testSum" time="0.0" classname="com.epam.unittesting.tests.SumCalculatorTest"/>
  <testcase name="sumDoubleTest" time="0.001" classname="com.epam.unittesting.tests.SumDoubleCalculatorTest"/>
  <testcase name="sumDoubleTest" time="0.0" classname="com.epam.unittesting.tests.SumDoubleCalculatorTest"/>
  <testcase name="sumDoubleTest" time="0.0" classname="com.epam.unittesting.tests.SumDoubleCalculatorTest"/>
  <testcase name="sumDoubleTest" time="0.0" classname="com.epam.unittesting.tests.SumDoubleCalculatorTest"/>
  <testcase name="sumDoubleTest" time="0.0" classname="com.epam.unittesting.tests.SumDoubleCalculatorTest"/>
  <testcase name="sumDoubleTest" time="0.0" classname="com.epam.unittesting.tests.SumDoubleCalculatorTest"/>
  <testcase name="sumDoubleTest" time="0.0" classname="com.epam.unittesting.tests.SumDoubleCalculatorTest"/>
  <testcase name="sumDoubleTest" time="0.0" classname="com.epam.unittesting.tests.SumDoubleCalculatorTest"/>
  <testcase name="sumDoubleTest" time="0.001" classname="com.epam.unittesting.tests.SumDoubleCalculatorTest">
    <failure type="java.lang.AssertionError" message="Invalid result of sum: expected [-28.7] but found [-28.700000000000003]">
      <![CDATA[java.lang.AssertionError: Invalid result of sum: expected [-28.7] but found [-28.700000000000003]
	at com.epam.unittesting.tests.SumDoubleCalculatorTest.sumDoubleTest(SumDoubleCalculatorTest.java:13)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
... Removed 20 stack frames]]>
    </failure>
  </testcase> <!-- sumDoubleTest -->
  <testcase name="sumDoubleTest" time="0.0" classname="com.epam.unittesting.tests.SumDoubleCalculatorTest">
    <failure type="java.lang.AssertionError" message="Invalid result of sum: expected [-28.8] but found [-28.799999999999997]">
      <![CDATA[java.lang.AssertionError: Invalid result of sum: expected [-28.8] but found [-28.799999999999997]
	at com.epam.unittesting.tests.SumDoubleCalculatorTest.sumDoubleTest(SumDoubleCalculatorTest.java:13)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
... Removed 20 stack frames]]>
    </failure>
  </testcase> <!-- sumDoubleTest -->
  <testcase name="sumDoubleTest" time="0.0" classname="com.epam.unittesting.tests.SumDoubleCalculatorTest"/>
  <testcase name="sumDoubleTest" time="0.0" classname="com.epam.unittesting.tests.SumDoubleCalculatorTest"/>
  <testcase name="sumDoubleTest" time="0.0" classname="com.epam.unittesting.tests.SumDoubleCalculatorTest"/>
  <testcase name="sumDoubleTest" time="0.0" classname="com.epam.unittesting.tests.SumDoubleCalculatorTest">
    <failure type="java.lang.AssertionError" message="Invalid result of sum: expected [-28.3] but found [-28.299999999999997]">
      <![CDATA[java.lang.AssertionError: Invalid result of sum: expected [-28.3] but found [-28.299999999999997]
	at com.epam.unittesting.tests.SumDoubleCalculatorTest.sumDoubleTest(SumDoubleCalculatorTest.java:13)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
... Removed 20 stack frames]]>
    </failure>
  </testcase> <!-- sumDoubleTest -->
  <testcase name="sumDoubleTest" time="0.0" classname="com.epam.unittesting.tests.SumDoubleCalculatorTest">
    <failure type="java.lang.AssertionError" message="Invalid result of sum: expected [-28.2] but found [-28.200000000000003]">
      <![CDATA[java.lang.AssertionError: Invalid result of sum: expected [-28.2] but found [-28.200000000000003]
	at com.epam.unittesting.tests.SumDoubleCalculatorTest.sumDoubleTest(SumDoubleCalculatorTest.java:13)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
... Removed 20 stack frames]]>
    </failure>
  </testcase> <!-- sumDoubleTest -->
  <testcase name="sumDoubleTest" time="0.001" classname="com.epam.unittesting.tests.SumDoubleCalculatorTest">
    <failure type="java.lang.AssertionError" message="Invalid result of sum: expected [-28.1] but found [-28.700000000000003]">
      <![CDATA[java.lang.AssertionError: Invalid result of sum: expected [-28.1] but found [-28.700000000000003]
	at com.epam.unittesting.tests.SumDoubleCalculatorTest.sumDoubleTest(SumDoubleCalculatorTest.java:13)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
... Removed 20 stack frames]]>
    </failure>
  </testcase> <!-- sumDoubleTest -->
  <testcase name="testSum1" time="0.0" classname="com.epam.unittesting.tests.SumCalculatorTest"/>
  <testcase name="testSum1" time="0.003" classname="com.epam.unittesting.tests.SumCalculatorTest"/>
  <testcase name="testSum1" time="0.001" classname="com.epam.unittesting.tests.SumCalculatorTest"/>
</testsuite> <!-- testSum -->
