<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="EPKZKARW0363" ignored="0" name="testCos" tests="2" failures="2" timestamp="30 Oct 2017 08:02:44 GMT" time="0.003" errors="0">
  <testcase name="cosTest" time="0.0" classname="com.epam.unittesting.tests.CosCalculatorTest">
    <failure type="java.lang.AssertionError" message="Invalid result of cos:  expected [0.54030230586814] but found [0.01745240643728351]">
      <![CDATA[java.lang.AssertionError: Invalid result of cos:  expected [0.54030230586814] but found [0.01745240643728351]
	at com.epam.unittesting.tests.CosCalculatorTest.cosTest(CosCalculatorTest.java:13)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
... Removed 20 stack frames]]>
    </failure>
  </testcase> <!-- cosTest -->
  <testcase name="cosTest" time="0.0" classname="com.epam.unittesting.tests.CosCalculatorTest">
    <failure type="java.lang.AssertionError" message="Invalid result of cos:  expected [0.96496602849211] but found [0.766044443118978]">
      <![CDATA[java.lang.AssertionError: Invalid result of cos:  expected [0.96496602849211] but found [0.766044443118978]
	at com.epam.unittesting.tests.CosCalculatorTest.cosTest(CosCalculatorTest.java:13)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
... Removed 20 stack frames]]>
    </failure>
  </testcase> <!-- cosTest -->
</testsuite> <!-- testCos -->
