<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="EPKZKARW0363" ignored="0" name="testIsNegative" tests="3" failures="2" timestamp="30 Oct 2017 08:02:44 GMT" time="0.002" errors="0">
  <testcase name="isNegativeTest" time="0.0" classname="com.epam.unittesting.tests.IsNegativeCalculatorTest">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at com.epam.unittesting.tests.IsNegativeCalculatorTest.isNegativeTest(IsNegativeCalculatorTest.java:13)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
... Removed 20 stack frames]]>
    </failure>
  </testcase> <!-- isNegativeTest -->
  <testcase name="isNegativeTest" time="0.001" classname="com.epam.unittesting.tests.IsNegativeCalculatorTest">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at com.epam.unittesting.tests.IsNegativeCalculatorTest.isNegativeTest(IsNegativeCalculatorTest.java:13)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
... Removed 20 stack frames]]>
    </failure>
  </testcase> <!-- isNegativeTest -->
  <testcase name="isNegativeTest" time="0.0" classname="com.epam.unittesting.tests.IsNegativeCalculatorTest"/>
</testsuite> <!-- testIsNegative -->
