<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="EPKZKARW0363" ignored="0" name="testSubtraction" tests="13" failures="5" timestamp="30 Oct 2017 08:02:44 GMT" time="0.046" errors="0">
  <testcase name="subTest" time="0.002" classname="com.epam.unittesting.tests.SubCalculatorTest"/>
  <testcase name="subTest" time="0.0" classname="com.epam.unittesting.tests.SubCalculatorTest"/>
  <testcase name="subTest" time="0.007" classname="com.epam.unittesting.tests.SubCalculatorTest"/>
  <testcase name="subTest" time="0.0" classname="com.epam.unittesting.tests.SubCalculatorTest"/>
  <testcase name="subTest" time="0.001" classname="com.epam.unittesting.tests.SubCalculatorTest"/>
  <testcase name="subDoubleTest" time="0.001" classname="com.epam.unittesting.tests.SubDoubleCalculatorTest"/>
  <testcase name="subDoubleTest" time="0.001" classname="com.epam.unittesting.tests.SubDoubleCalculatorTest"/>
  <testcase name="subDoubleTest" time="0.0" classname="com.epam.unittesting.tests.SubDoubleCalculatorTest"/>
  <testcase name="subDoubleTest" time="0.0" classname="com.epam.unittesting.tests.SubDoubleCalculatorTest">
    <failure type="java.lang.AssertionError" message="Invalid result of subtraction:  expected [36.01] but found [36.010000000000005]">
      <![CDATA[java.lang.AssertionError: Invalid result of subtraction:  expected [36.01] but found [36.010000000000005]
	at com.epam.unittesting.tests.SubDoubleCalculatorTest.subDoubleTest(SubDoubleCalculatorTest.java:13)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
... Removed 20 stack frames]]>
    </failure>
  </testcase> <!-- subDoubleTest -->
  <testcase name="subDoubleTest" time="0.0" classname="com.epam.unittesting.tests.SubDoubleCalculatorTest">
    <failure type="java.lang.AssertionError" message="Invalid result of subtraction:  expected [36.1] but found [36.099999999999994]">
      <![CDATA[java.lang.AssertionError: Invalid result of subtraction:  expected [36.1] but found [36.099999999999994]
	at com.epam.unittesting.tests.SubDoubleCalculatorTest.subDoubleTest(SubDoubleCalculatorTest.java:13)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
... Removed 20 stack frames]]>
    </failure>
  </testcase> <!-- subDoubleTest -->
  <testcase name="subDoubleTest" time="0.0" classname="com.epam.unittesting.tests.SubDoubleCalculatorTest">
    <failure type="java.lang.AssertionError" message="Invalid result of subtraction:  expected [36.4] but found [36.400000000000006]">
      <![CDATA[java.lang.AssertionError: Invalid result of subtraction:  expected [36.4] but found [36.400000000000006]
	at com.epam.unittesting.tests.SubDoubleCalculatorTest.subDoubleTest(SubDoubleCalculatorTest.java:13)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
... Removed 20 stack frames]]>
    </failure>
  </testcase> <!-- subDoubleTest -->
  <testcase name="subDoubleTest" time="0.0" classname="com.epam.unittesting.tests.SubDoubleCalculatorTest">
    <failure type="java.lang.AssertionError" message="Invalid result of subtraction:  expected [36.6] but found [36.599999999999994]">
      <![CDATA[java.lang.AssertionError: Invalid result of subtraction:  expected [36.6] but found [36.599999999999994]
	at com.epam.unittesting.tests.SubDoubleCalculatorTest.subDoubleTest(SubDoubleCalculatorTest.java:13)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
... Removed 20 stack frames]]>
    </failure>
  </testcase> <!-- subDoubleTest -->
  <testcase name="subDoubleTest" time="0.0" classname="com.epam.unittesting.tests.SubDoubleCalculatorTest">
    <failure type="java.lang.AssertionError" message="Invalid result of subtraction:  expected [36.9] but found [36.900000000000006]">
      <![CDATA[java.lang.AssertionError: Invalid result of subtraction:  expected [36.9] but found [36.900000000000006]
	at com.epam.unittesting.tests.SubDoubleCalculatorTest.subDoubleTest(SubDoubleCalculatorTest.java:13)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
... Removed 20 stack frames]]>
    </failure>
  </testcase> <!-- subDoubleTest -->
</testsuite> <!-- testSubtraction -->
